name: Build for Windows MSVC

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-type=Release" >> "$GITHUB_OUTPUT"
          echo "build-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"
          echo "out-dir=${{ github.workspace }}\build\output" >> "$GITHUB_OUTPUT"
          echo "bin-dir=${{ github.workspace }}\build\output\bin" >> "$GITHUB_OUTPUT"

      - name: Install Qt
        id: install-qt-msvc
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Install RE2 on Windows
        run: vcpkg install re2:x64-windows-static-md
        id: install-re2-windows

      - name: CMake Configure
        run: >
          cmake -B ${{ steps.strings.outputs.build-dir }}
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
          -DCMAKE_BUILD_TYPE=${{ steps.strings.outputs.build-type }}
          -S ${{ github.workspace }}

      - name: CMake Build
        run: >
          cmake --build ${{ steps.strings.outputs.build-dir }}
          --config ${{ steps.strings.outputs.build-type }}

      - name: Run Tests
        working-directory: ${{ steps.strings.outputs.build-dir }}/tests
        run: ctest -C ${{ steps.strings.outputs.build-type }} --output-on-failure

      - name: CMake Install
        run: >
          cmake --install ${{ steps.strings.outputs.build-dir }}
          --config ${{ steps.strings.outputs.build-type }}
          --prefix ${{ steps.strings.outputs.out-dir }}

      - name: Get Qt Dependency Libs
        run: windeployqt --release --no-translations ${{ steps.strings.outputs.bin-dir }}\qlogexplorer.exe

      - name: Build Installer Application
        id: build-installer-msvc
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: packaging/win/innosetup.iss
          options: |
            /O+
            /DSrcDir=${{ github.workspace }}
            /DOutBinDir=${{ steps.strings.outputs.bin-dir }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QLogExplorer-Msvc-Bundle
          path: ${{ steps.strings.outputs.bin-dir }}\*
